version: '3.5'

services:

  #nome do servico
  vue-sales:

    #construido a partir de uma imagem customizada em ./image
    image: vue-sales
    
    #nome do conteiner
    container_name: vue-sales

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/usr/src/app"

    #porta a ser exposta
    ports:
      - 8080:8080
  
    #artifício para manter o container aberto
    tty: true
